env = Environment(CCFLAGS='-O2 -DTIXML_USE_STL')

sources = [
	'tinyxml.cpp',
	'tinyxmlerror.cpp',
	'tinyxmlparser.cpp',
]

objs = []
for source in sources:
	objs.append(env.Object(source))

Return('objs')
